/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1WJmnIOdJuD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function scr() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-primary text-primary-foreground py-2 px-4 flex items-center justify-between sm:py-4 sm:px-6">
        <div className="flex items-center gap-2">
          <CameraIcon className="w-6 h-6" />
          <h1 className="text-lg font-bold sm:text-xl">Security Camera Tracker</h1>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost">
            <SettingsIcon className="w-5 h-5" />
            <span className="sr-only">Settings</span>
          </Button>
          <Button variant="ghost">
            <HandHelpingIcon className="w-5 h-5" />
            <span className="sr-only">Help</span>
          </Button>
        </div>
      </header>
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-8 p-8 overflow-y-auto">
        <div className="bg-background rounded-lg border p-6 flex flex-col gap-4">
          <div className="aspect-video bg-muted rounded-md overflow-hidden relative">
            <video className="w-full h-full object-cover">
              <source
                src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                type="video/mp4"
              />
            </video>
            <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
              <div className="text-sm text-muted-foreground">Live Camera Feed</div>
            </div>
          </div>
          <div className="flex items-center justify-between">
            <div className="text-sm text-muted-foreground">Live feed: {new Date().toLocaleTimeString()}</div>
            <div className="flex items-center gap-2">
              <Button variant="ghost" size="icon">
                <PauseIcon className="w-5 h-5" />
                <span className="sr-only">Pause</span>
              </Button>
              <Button variant="ghost" size="icon">
                <CircleStopIcon className="w-5 h-5" />
                <span className="sr-only">Stop</span>
              </Button>
            </div>
          </div>
        </div>
        <div className="bg-background rounded-lg border p-6 flex flex-col gap-4 overflow-y-auto">
          <div className="grid grid-cols-1 gap-4">
            <div className="bg-muted rounded-md p-4 flex flex-col gap-2">
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  alt="License Plate"
                  width={100}
                  height={100}
                  className="rounded-md"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
                <div>
                  <div className="text-sm text-muted-foreground">License Plate Detected</div>
                  <div className="text-2xl font-bold">ABC 1234</div>
                  <div className="text-sm text-muted-foreground">Time Detected: {new Date().toLocaleTimeString()}</div>
                </div>
              </div>
              <div className="text-sm text-muted-foreground">Allowed License Plate</div>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col gap-2">
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  alt="License Plate"
                  width={100}
                  height={100}
                  className="rounded-md"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
                <div>
                  <div className="text-sm text-muted-foreground">License Plate Detected</div>
                  <div className="text-2xl font-bold">XYZ 5678</div>
                  <div className="text-sm text-muted-foreground">Time Detected: {new Date().toLocaleTimeString()}</div>
                </div>
              </div>
              <div className="text-sm text-muted-foreground">Allowed License Plate</div>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col gap-2">
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  alt="License Plate"
                  width={100}
                  height={100}
                  className="rounded-md"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
                <div>
                  <div className="text-sm text-muted-foreground">License Plate Detected</div>
                  <div className="text-2xl font-bold">PQR 9012</div>
                  <div className="text-sm text-muted-foreground">Time Detected: {new Date().toLocaleTimeString()}</div>
                </div>
              </div>
              <div className="text-sm text-muted-foreground">Allowed License Plate</div>
            </div>
            <div className="bg-muted rounded-md p-4 flex flex-col gap-2">
              <div className="flex items-start gap-4">
                <img
                  src="/placeholder.svg"
                  alt="License Plate"
                  width={100}
                  height={100}
                  className="rounded-md"
                  style={{ aspectRatio: "100/100", objectFit: "cover" }}
                />
                <div>
                  <div className="text-sm text-muted-foreground">License Plate Detected</div>
                  <div className="text-2xl font-bold">STU 3456</div>
                  <div className="text-sm text-muted-foreground">Time Detected: {new Date().toLocaleTimeString()}</div>
                </div>
              </div>
              <div className="text-sm text-muted-foreground">Allowed License Plate</div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function CameraIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
      <circle cx="12" cy="13" r="3" />
    </svg>
  )
}


function CircleStopIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <rect width="6" height="6" x="9" y="9" />
    </svg>
  )
}


function HandHelpingIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 12h2a2 2 0 1 0 0-4h-3c-.6 0-1.1.2-1.4.6L3 14" />
      <path d="m7 18 1.6-1.4c.3-.4.8-.6 1.4-.6h4c1.1 0 2.1-.4 2.8-1.2l4.6-4.4a2 2 0 0 0-2.75-2.91l-4.2 3.9" />
      <path d="m2 13 6 6" />
    </svg>
  )
}


function PauseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="14" y="4" width="4" height="16" rx="1" />
      <rect x="6" y="4" width="4" height="16" rx="1" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
